.ALIASES
R_RB5           RB5(1=N00682 2=N00977 )
V_VDC           VDC(+=N00977 -=0 )
R_R1            R1(1=0 2=VOUT )
R_RC3           RC3(1=N02604 2=N00977 )
C_C1            C1(1=N02636 2=VOUT )
R_RB6           RB6(1=0 2=N00682 )
R_RE3           RE3(1=0 2=N02636 )
C_C2            C2(1=VI 2=N00682 )
V_V1            V1(+=VI -=0 )
Q_Q3            Q3(c=N02604 b=N00682 e=N02636 )
_    _(Vout=VOUT)
_    _(Vi=VI)
.ENDALIASES
